name: Punch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-21.10

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install libsqlite3-dev build-essential
    - run: bash build.sh
    - run: cd ~
    - run: source ~/.bashrc
    - run: punch hello
    - run: ls hello
