name: Punch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install libsqlite3-dev build-essential
    - run: bash build.sh
    - run: cargo run --release -- hello
    - run: ls hello
    - run: cargo run --release -- -d hello
    - run: if [[ -f hello ]]; then exit 1; fi
