name: Punch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
    run: sudo apt install libsqlite3-dev build-essential
    - name: Build
    run: bash build.sh
    - name: Test
    run: ./target/release/punch hello
    run: ls hello
