name: Punch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20-04

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install libsqlite3-dev build-essential
    - run: bash build.sh
    - run: ./target/release/punch hello
    - run: ls hello
