name: Punch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install -y libsqlite3-dev build-essential
    - run: bash build.sh
    - run: cargo run --release -- hello && ls hello
    - run: cargo run --release -- -d hello && [[ -f hello ]] && exit 1
